using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Poppy_Universe_Engine
{
    /// <summary>
    /// Data structure representing a user's predicted preference matrix, generated by a 
    /// Neural Network (NN) or other advanced machine learning model (Layer 4).
    /// These scores are used to apply the final, most influential boost to recommendations.
    /// </summary>
    public class Layer4_User_NN_Object
    {
        /// <summary>
        /// The unique identifier for the user to whom this prediction matrix belongs.
        /// </summary>
        public int User_ID { get; set; }

        // --- STARS: Predicted Spectral Type Preferences ---
        // These values represent the NN's prediction (e.g., on a 0-10 scale) of how 
        // much the user is likely to prefer stars of each spectral class.
        // 
        public double A { get; set; } // Blue-White Stars
        public double B { get; set; } // Blue Stars
        public double F { get; set; } // White Stars
        public double G { get; set; } // Yellow Stars
        public double K { get; set; } // Orange Stars
        public double M { get; set; } // Red Dwarf Stars
        public double O { get; set; } // Blue Giant Stars

        // --- PLANETS: Predicted Planet Category Preferences ---
        // NN prediction of preference for different planetary classifications.
        public double DwarfPlanet { get; set; }
        public double GasGiant { get; set; } // Jupiter, Saturn
        public double IceGiant { get; set; } // Uranus, Neptune
        public double Terrestrial { get; set; } // Mercury, Venus, Earth, Mars

        // --- MOONS: Predicted Parent Planet Preferences ---
        // NN prediction of preference for the moon systems associated with specific parent bodies.
        public double Earth { get; set; }
        public double Eris { get; set; }
        public double Haumea { get; set; }
        public double Jupiter { get; set; }
        public double Makemake { get; set; }
        public double Mars { get; set; }
        public double Neptune { get; set; }
        public double Pluto { get; set; }
        public double Saturn { get; set; }
        public double Uranus { get; set; }
    }
}